from rfx_base import config

LOG_LEVEL = config.LOG_LEVEL
DB_DSN = config.DB_DSN

USER_PROFILE_SCHEMA = config.RFX_USER_SCHEMA
POLICY_SCHEMA = config.RFX_USER_SCHEMA
POLICY_TABLE = "_policy__user_profile"
REALM = 'rfx'
REALM_URL_MAPPER = None

# Guest Authentication Settings
VERIFICATION_CODE_LENGTH = 6
VERIFICATION_TTL_MINUTES = 15
MAX_REQUESTS_PER_WINDOW = 3
RATE_LIMIT_WINDOW_MINUTES = 15
MAX_VERIFICATION_ATTEMPTS = 5
GUEST_SESSION_TTL_HOURS = 24
VERIFICATION_CODE_LENGTH = 6
VERIFICATION_TTL_MINUTES = 15
MAX_REQUESTS_PER_WINDOW = 3
RATE_LIMIT_WINDOW_MINUTES = 15
