from rfx_base import config
from fluvius.fastapi import config as fastapi_config

DB_DSN = config.DB_DSN

USER_PROFILE_SCHEMA = config.RFX_USER_SCHEMA
POLICY_SCHEMA = config.RFX_USER_SCHEMA
POLICY_TABLE = "_policy__user_profile"
REALM = 'rfx'
REALM_URL_MAPPER = None

# Guest Authentication Settings
VERIFICATION_CODE_LENGTH = 6
VERIFICATION_TTL_MINUTES = 15
MAX_REQUESTS_PER_WINDOW = 3
INVITATION_MAX_REQUESTS_PER_WINDOW = 10
RATE_LIMIT_WINDOW_MINUTES = 15
MAX_VERIFICATION_ATTEMPTS = 5
GUEST_SESSION_TTL_HOURS = 24
SES_GUEST_FIELD = "guest"
SES_USER_FIELD = "user"
SES_ID_TOKEN_FIELD = "id_token"
COOKIE_HTTPS_ONLY = True
COOKIE_SAME_SITE_POLICY = "lax"
DEFAULT_LOGOUT_REDIRECT_URI = fastapi_config.DEFAULT_LOGOUT_REDIRECT_URI
DEFAULT_SIGNIN_REDIRECT_URI = fastapi_config.DEFAULT_SIGNIN_REDIRECT_URI
VALIDATE_CSRF_TOKEN = fastapi_config.VALIDATE_CSRF_TOKEN

# Guest JWT Settings
GUEST_JWT_SECRET = None
GUEST_JWT_ALGORITHM = "HS256"
GUEST_JWT_ISSUER = "rfx-user-guest-auth"

API_BASE_URL = None
NAMESPACE = "user-profile"
