"""notify

Revision ID: b9fbf9ef75c1
Revises: 
Create Date: 2025-11-11 18:09:28.244392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9fbf9ef75c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEBHOOK', 'INAPP', name='notificationchannelenum', schema='ttp_notify'), nullable=False),
    sa.Column('provider_type', sa.Enum('SMTP', 'SENDGRID', 'SES', 'TWILIO', 'SNS', 'FIREBASE', 'MQTT', 'CUSTOM', name='providertypeenum', schema='ttp_notify'), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'HTML', 'MARKDOWN', 'JSON', name='contenttypeenum', schema='ttp_notify'), nullable=True),
    sa.Column('recipient_address', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'REJECTED', 'BOUNCED', name='notificationstatusenum', schema='ttp_notify'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriorityenum', schema='ttp_notify'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=255), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('provider_message_id', sa.String(length=512), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ttp_notify'
    )
    op.create_table('notification_preference',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEBHOOK', 'INAPP', name='notificationchannelenum', schema='ttp_notify'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('device_token', sa.String(length=512), nullable=True),
    sa.Column('opt_in', sa.Boolean(), nullable=False),
    sa.Column('frequency_limit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('quiet_hours_timezone', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('user_id', 'channel', name='uq_user_channel_preference'),
    schema='ttp_notify'
    )
    op.create_table('notification_template',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEBHOOK', 'INAPP', name='notificationchannelenum', schema='ttp_notify'), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('subject_template', sa.String(length=512), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'HTML', 'MARKDOWN', 'JSON', name='contenttypeenum', schema='ttp_notify'), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('tenant_id', 'app_id', 'key', 'version', 'channel', 'locale', name='uq_notify_template_scope'),
    schema='ttp_notify'
    )
    op.create_table('notification_delivery_log',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('SMTP', 'SENDGRID', 'SES', 'TWILIO', 'SNS', 'FIREBASE', 'MQTT', 'CUSTOM', name='providertypeenum', schema='ttp_notify'), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'REJECTED', 'BOUNCED', name='notificationstatusenum', schema='ttp_notify'), nullable=False),
    sa.Column('status_code', sa.String(length=64), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['ttp_notify.notification._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ttp_notify'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_delivery_log', schema='ttp_notify')
    op.drop_table('notification_template', schema='ttp_notify')
    op.drop_table('notification_preference', schema='ttp_notify')
    op.drop_table('notification', schema='ttp_notify')
    # ### end Alembic commands ###
