"""test user

Revision ID: 9a5904cc863d
Revises: 
Create Date: 2025-11-07 13:25:06.810323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a5904cc863d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('_txt', postgresql.TSVECTOR(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('ref__action',
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_user_test'
    )
    op.create_table('ref__organization_type',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_user_test'
    )
    op.create_table('ref__realm',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_user_test'
    )
    op.create_table('ref__role_type',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_user_test'
    )
    op.create_table('user',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name__family', sa.String(length=1024), nullable=True),
    sa.Column('name__given', sa.String(length=1024), nullable=True),
    sa.Column('name__middle', sa.String(length=1024), nullable=True),
    sa.Column('name__prefix', sa.String(length=1024), nullable=True),
    sa.Column('name__suffix', sa.String(length=1024), nullable=True),
    sa.Column('telecom__email', sa.String(length=1024), nullable=True),
    sa.Column('telecom__phone', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('verified_email', sa.String(length=1024), nullable=True),
    sa.Column('verified_phone', sa.String(length=1024), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='userstatusenum'), nullable=False),
    sa.Column('realm_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_request', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('organization',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=9), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('system_entity', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('system_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organizationstatusenum'), nullable=False),
    sa.Column('invitation_code', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['rfx_user_test.ref__organization_type.key'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('ref__system_role',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_default_signer', sa.Boolean(), nullable=True),
    sa.Column('default_role', sa.Boolean(), nullable=True),
    sa.Column('official_role', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('role_type', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['role_type'], ['rfx_user_test.ref__role_type.key'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('user_identity',
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('telecom__email', sa.String(length=255), nullable=True),
    sa.Column('telecom__phone', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('user_status',
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='userstatusenum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='userstatusenum'), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('organization_delegated_access',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('delegated_organization_id', sa.UUID(), nullable=True),
    sa.Column('access_scope', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['delegated_organization_id'], ['rfx_user_test.organization._id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx_user_test.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('organization_role',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('_txt', postgresql.TSVECTOR(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx_user_test.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('organization_status',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organizationstatusenum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organizationstatusenum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx_user_test.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('profile',
    sa.Column('access_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('address__city', sa.String(length=1024), nullable=True),
    sa.Column('address__country', sa.String(length=1024), nullable=True),
    sa.Column('address__line1', sa.String(length=1024), nullable=True),
    sa.Column('address__line2', sa.String(length=1024), nullable=True),
    sa.Column('address__postal', sa.String(length=1024), nullable=True),
    sa.Column('address__state', sa.String(length=1024), nullable=True),
    sa.Column('picture_id', sa.UUID(), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name__family', sa.String(length=1024), nullable=True),
    sa.Column('name__given', sa.String(length=1024), nullable=True),
    sa.Column('name__middle', sa.String(length=1024), nullable=True),
    sa.Column('name__prefix', sa.String(length=1024), nullable=True),
    sa.Column('name__suffix', sa.String(length=1024), nullable=True),
    sa.Column('realm', sa.String(length=1024), nullable=True),
    sa.Column('svc_access', sa.String(length=1024), nullable=True),
    sa.Column('svc_secret', sa.String(length=1024), nullable=True),
    sa.Column('user_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('telecom__email', sa.String(length=1024), nullable=True),
    sa.Column('telecom__fax', sa.String(length=1024), nullable=True),
    sa.Column('telecom__phone', sa.String(length=1024), nullable=True),
    sa.Column('tfa_method', sa.String(length=1024), nullable=True),
    sa.Column('tfa_token', sa.String(length=1024), nullable=True),
    sa.Column('two_factor_authentication', sa.Boolean(), nullable=True),
    sa.Column('upstream_user_id', sa.UUID(), nullable=True),
    sa.Column('user_type', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('verified_email', sa.String(length=1024), nullable=True),
    sa.Column('verified_phone', sa.String(length=1024), nullable=True),
    sa.Column('primary_language', sa.String(length=255), nullable=True),
    sa.Column('npi', sa.String(length=255), nullable=True),
    sa.Column('verified_npi', sa.String(length=255), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('system_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profilestatusenum'), nullable=False),
    sa.Column('preferred_name', sa.String(length=255), nullable=True),
    sa.Column('default_theme', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('current_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx_user_test.organization._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('user_action',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='useractionstatusenum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['rfx_user_test.ref__action.key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx_user_test.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('user_session',
    sa.Column('source', sa.Enum('WEB', 'MOBILE', 'KEYCLOAK', 'MOBILE_KC', name='usersourceenum'), nullable=True),
    sa.Column('telecom__email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx_user_test.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('user_verification',
    sa.Column('verification', sa.String(length=1024), nullable=False),
    sa.Column('last_sent_email', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx_user_test.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('invitation',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitationstatusenum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx_user_test.organization._id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx_user_test.profile._id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['rfx_user_test.user._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx_user_test.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('profile_group',
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['rfx_user_test.group._id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx_user_test.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('profile_location',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=15), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx_user_test.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('profile_role',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('role_key', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_source', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx_user_test.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('profile_status',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profilestatusenum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profilestatusenum'), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx_user_test.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    op.create_table('invitation_status',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitationstatusenum'), nullable=False),
    sa.Column('dst_state', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitationstatusenum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['rfx_user_test.invitation._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_user_test'
    )
    rfx_user_test__profile = PGView(
        schema="rfx_user_test",
        signature="_profile",
        definition='SELECT profile._created,\n    profile._creator,\n    profile._deleted,\n    profile._etag,\n    profile._id,\n    profile._updated,\n    profile._updater,\n    profile.access_tags,\n    profile.active,\n    profile.address__city,\n    profile.address__country,\n    profile.address__line1,\n    profile.address__line2,\n    profile.address__postal,\n    profile.address__state,\n    profile.picture_id,\n    profile.birthdate,\n    profile.expiration_date,\n    profile.gender,\n    profile.language,\n    profile.last_login,\n    profile.name__family,\n    profile.name__given,\n    profile.name__middle,\n    profile.name__prefix,\n    profile.name__suffix,\n    profile.realm,\n    profile.svc_access,\n    profile.svc_secret,\n    profile.user_tag,\n    profile.telecom__email,\n    profile.telecom__fax,\n    profile.telecom__phone,\n    profile.tfa_method,\n    profile.tfa_token,\n    profile.two_factor_authentication,\n    profile.upstream_user_id,\n    profile.user_type,\n    profile.username,\n    profile.verified_email,\n    profile.verified_phone,\n    profile.primary_language,\n    profile.npi,\n    profile.verified_npi,\n    profile.last_sync,\n    profile.is_super_admin,\n    profile.system_tag,\n    profile.user_id,\n    profile.current_profile,\n    profile.organization_id,\n    profile.preferred_name,\n    profile.default_theme,\n    profile._realm,\n    profile.status\n    FROM rfx_user.profile'
    )
    op.create_entity(rfx_user_test__profile)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rfx_user_test__profile = PGView(
        schema="rfx_user_test",
        signature="_profile",
        definition='SELECT profile._created,\n    profile._creator,\n    profile._deleted,\n    profile._etag,\n    profile._id,\n    profile._updated,\n    profile._updater,\n    profile.access_tags,\n    profile.active,\n    profile.address__city,\n    profile.address__country,\n    profile.address__line1,\n    profile.address__line2,\n    profile.address__postal,\n    profile.address__state,\n    profile.picture_id,\n    profile.birthdate,\n    profile.expiration_date,\n    profile.gender,\n    profile.language,\n    profile.last_login,\n    profile.name__family,\n    profile.name__given,\n    profile.name__middle,\n    profile.name__prefix,\n    profile.name__suffix,\n    profile.realm,\n    profile.svc_access,\n    profile.svc_secret,\n    profile.user_tag,\n    profile.telecom__email,\n    profile.telecom__fax,\n    profile.telecom__phone,\n    profile.tfa_method,\n    profile.tfa_token,\n    profile.two_factor_authentication,\n    profile.upstream_user_id,\n    profile.user_type,\n    profile.username,\n    profile.verified_email,\n    profile.verified_phone,\n    profile.primary_language,\n    profile.npi,\n    profile.verified_npi,\n    profile.last_sync,\n    profile.is_super_admin,\n    profile.system_tag,\n    profile.user_id,\n    profile.current_profile,\n    profile.organization_id,\n    profile.preferred_name,\n    profile.default_theme,\n    profile._realm,\n    profile.status\n    FROM rfx_user.profile'
    )
    op.drop_entity(rfx_user_test__profile)

    op.drop_table('invitation_status', schema='rfx_user_test')
    op.drop_table('profile_status', schema='rfx_user_test')
    op.drop_table('profile_role', schema='rfx_user_test')
    op.drop_table('profile_location', schema='rfx_user_test')
    op.drop_table('profile_group', schema='rfx_user_test')
    op.drop_table('invitation', schema='rfx_user_test')
    op.drop_table('user_verification', schema='rfx_user_test')
    op.drop_table('user_session', schema='rfx_user_test')
    op.drop_table('user_action', schema='rfx_user_test')
    op.drop_table('profile', schema='rfx_user_test')
    op.drop_table('organization_status', schema='rfx_user_test')
    op.drop_table('organization_role', schema='rfx_user_test')
    op.drop_table('organization_delegated_access', schema='rfx_user_test')
    op.drop_table('user_status', schema='rfx_user_test')
    op.drop_table('user_identity', schema='rfx_user_test')
    op.drop_table('ref__system_role', schema='rfx_user_test')
    op.drop_table('organization', schema='rfx_user_test')
    op.drop_table('user', schema='rfx_user_test')
    op.drop_table('ref__role_type', schema='rfx_user_test')
    op.drop_table('ref__realm', schema='rfx_user_test')
    op.drop_table('ref__organization_type', schema='rfx_user_test')
    op.drop_table('ref__action', schema='rfx_user_test')
    op.drop_table('group', schema='rfx_user_test')
    # ### end Alembic commands ###
