"""test user#2

Revision ID: 87f6449c1938
Revises: aefd82bc7460
Create Date: 2025-11-07 13:33:45.784538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '87f6449c1938'
down_revision: Union[str, Sequence[str], None] = 'aefd82bc7460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rfx_user_test__profile = PGView(
        schema="rfx_user_test",
        signature="_profile",
        definition='SELECT profile._created,\n    profile._creator,\n    profile._deleted,\n    profile._etag,\n    profile._id,\n    profile._updated,\n    profile._updater,\n    profile.access_tags,\n    profile.active,\n    profile.address__city,\n    profile.address__country,\n    profile.address__line1,\n    profile.address__line2,\n    profile.address__postal,\n    profile.address__state,\n    profile.picture_id,\n    profile.birthdate,\n    profile.expiration_date,\n    profile.gender,\n    profile.language,\n    profile.last_login,\n    profile.name__family,\n    profile.name__given,\n    profile.name__middle,\n    profile.name__prefix,\n    profile.name__suffix,\n    profile.realm,\n    profile.svc_access,\n    profile.svc_secret,\n    profile.user_tag,\n    profile.telecom__email,\n    profile.telecom__fax,\n    profile.telecom__phone,\n    profile.tfa_method,\n    profile.tfa_token,\n    profile.two_factor_authentication,\n    profile.upstream_user_id,\n    profile.user_type,\n    profile.username,\n    profile.verified_email,\n    profile.verified_phone,\n    profile.primary_language,\n    profile.npi,\n    profile.verified_npi,\n    profile.last_sync,\n    profile.is_super_admin,\n    profile.system_tag,\n    profile.user_id,\n    profile.current_profile,\n    profile.organization_id,\n    profile.preferred_name,\n    profile.default_theme,\n    profile._realm,\n    profile.status\n    FROM rfx_user_test.profile'
    )
    op.create_entity(rfx_user_test__profile)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rfx_user_test__profile = PGView(
        schema="rfx_user_test",
        signature="_profile",
        definition='SELECT profile._created,\n    profile._creator,\n    profile._deleted,\n    profile._etag,\n    profile._id,\n    profile._updated,\n    profile._updater,\n    profile.access_tags,\n    profile.active,\n    profile.address__city,\n    profile.address__country,\n    profile.address__line1,\n    profile.address__line2,\n    profile.address__postal,\n    profile.address__state,\n    profile.picture_id,\n    profile.birthdate,\n    profile.expiration_date,\n    profile.gender,\n    profile.language,\n    profile.last_login,\n    profile.name__family,\n    profile.name__given,\n    profile.name__middle,\n    profile.name__prefix,\n    profile.name__suffix,\n    profile.realm,\n    profile.svc_access,\n    profile.svc_secret,\n    profile.user_tag,\n    profile.telecom__email,\n    profile.telecom__fax,\n    profile.telecom__phone,\n    profile.tfa_method,\n    profile.tfa_token,\n    profile.two_factor_authentication,\n    profile.upstream_user_id,\n    profile.user_type,\n    profile.username,\n    profile.verified_email,\n    profile.verified_phone,\n    profile.primary_language,\n    profile.npi,\n    profile.verified_npi,\n    profile.last_sync,\n    profile.is_super_admin,\n    profile.system_tag,\n    profile.user_id,\n    profile.current_profile,\n    profile.organization_id,\n    profile.preferred_name,\n    profile.default_theme,\n    profile._realm,\n    profile.status\n    FROM rfx_user_test.profile'
    )
    op.drop_entity(rfx_user_test__profile)

    # ### end Alembic commands ###
