"""SUCCESS - using config for schema

Revision ID: cc07d5c54a4c
Revises: 8438872bd483
Create Date: 2025-11-06 18:23:16.607936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc07d5c54a4c'
down_revision: Union[str, Sequence[str], None] = '8438872bd483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('group',
    sa.Column('_txt', postgresql.TSVECTOR(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('ref__action',
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx__user'
    )
    op.create_table('ref__organization_type',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx__user'
    )
    op.create_table('ref__realm',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx__user'
    )
    op.create_table('ref__role_type',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx__user'
    )
    op.create_table('user',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name__family', sa.String(length=1024), nullable=True),
    sa.Column('name__given', sa.String(length=1024), nullable=True),
    sa.Column('name__middle', sa.String(length=1024), nullable=True),
    sa.Column('name__prefix', sa.String(length=1024), nullable=True),
    sa.Column('name__suffix', sa.String(length=1024), nullable=True),
    sa.Column('telecom__email', sa.String(length=1024), nullable=True),
    sa.Column('telecom__phone', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('verified_email', sa.String(length=1024), nullable=True),
    sa.Column('verified_phone', sa.String(length=1024), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='user_status_enum'), nullable=False),
    sa.Column('realm_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_request', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('organization',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=9), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('system_entity', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('system_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organization_status_enum'), nullable=False),
    sa.Column('invitation_code', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['rfx__user.ref__organization_type.key'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('ref__system_role',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_default_signer', sa.Boolean(), nullable=True),
    sa.Column('default_role', sa.Boolean(), nullable=True),
    sa.Column('official_role', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('role_type', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['role_type'], ['rfx__user.ref__role_type.key'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('user_identity',
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('telecom__email', sa.String(length=255), nullable=True),
    sa.Column('telecom__phone', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('user_status',
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='user_status_enum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', name='user_status_enum'), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('organization_delegated_access',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('delegated_organization_id', sa.UUID(), nullable=True),
    sa.Column('access_scope', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['delegated_organization_id'], ['rfx__user.organization._id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx__user.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('organization_role',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('_txt', postgresql.TSVECTOR(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx__user.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('organization_status',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organization_status_enum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'SETUP', 'REVIEW', 'DEACTIVATED', name='organization_status_enum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx__user.organization._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('profile',
    sa.Column('access_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('address__city', sa.String(length=1024), nullable=True),
    sa.Column('address__country', sa.String(length=1024), nullable=True),
    sa.Column('address__line1', sa.String(length=1024), nullable=True),
    sa.Column('address__line2', sa.String(length=1024), nullable=True),
    sa.Column('address__postal', sa.String(length=1024), nullable=True),
    sa.Column('address__state', sa.String(length=1024), nullable=True),
    sa.Column('picture_id', sa.UUID(), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name__family', sa.String(length=1024), nullable=True),
    sa.Column('name__given', sa.String(length=1024), nullable=True),
    sa.Column('name__middle', sa.String(length=1024), nullable=True),
    sa.Column('name__prefix', sa.String(length=1024), nullable=True),
    sa.Column('name__suffix', sa.String(length=1024), nullable=True),
    sa.Column('realm', sa.String(length=1024), nullable=True),
    sa.Column('svc_access', sa.String(length=1024), nullable=True),
    sa.Column('svc_secret', sa.String(length=1024), nullable=True),
    sa.Column('user_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('telecom__email', sa.String(length=1024), nullable=True),
    sa.Column('telecom__fax', sa.String(length=1024), nullable=True),
    sa.Column('telecom__phone', sa.String(length=1024), nullable=True),
    sa.Column('tfa_method', sa.String(length=1024), nullable=True),
    sa.Column('tfa_token', sa.String(length=1024), nullable=True),
    sa.Column('two_factor_authentication', sa.Boolean(), nullable=True),
    sa.Column('upstream_user_id', sa.UUID(), nullable=True),
    sa.Column('user_type', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('verified_email', sa.String(length=1024), nullable=True),
    sa.Column('verified_phone', sa.String(length=1024), nullable=True),
    sa.Column('primary_language', sa.String(length=255), nullable=True),
    sa.Column('npi', sa.String(length=255), nullable=True),
    sa.Column('verified_npi', sa.String(length=255), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('system_tag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profile_status_enum'), nullable=False),
    sa.Column('preferred_name', sa.String(length=255), nullable=True),
    sa.Column('default_theme', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('current_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx__user.organization._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('user_action',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='user_action_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['rfx__user.ref__action.key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx__user.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('user_session',
    sa.Column('source', sa.Enum('WEB', 'MOBILE', 'KEYCLOAK', 'MOBILE_KC', name='user_source_enum'), nullable=True),
    sa.Column('telecom__email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx__user.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('user_verification',
    sa.Column('verification', sa.String(length=1024), nullable=False),
    sa.Column('last_sent_email', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_identity_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.ForeignKeyConstraint(['user_identity_id'], ['rfx__user.user_identity._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('invitation',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitation_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['rfx__user.organization._id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx__user.profile._id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['rfx__user.user._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rfx__user.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('profile_group',
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['rfx__user.group._id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx__user.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('profile_location',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=15), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx__user.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('profile_role',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('role_key', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_source', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx__user.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('profile_status',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profile_status_enum'), nullable=False),
    sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'ORGANIZATION_DEACTIVATED', name='profile_status_enum'), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rfx__user.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    op.create_table('invitation_status',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitation_status_enum'), nullable=False),
    sa.Column('dst_state', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REJECTED', name='invitation_status_enum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['rfx__user.invitation._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx__user'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_status', schema='rfx__user')
    op.drop_table('profile_status', schema='rfx__user')
    op.drop_table('profile_role', schema='rfx__user')
    op.drop_table('profile_location', schema='rfx__user')
    op.drop_table('profile_group', schema='rfx__user')
    op.drop_table('invitation', schema='rfx__user')
    op.drop_table('user_verification', schema='rfx__user')
    op.drop_table('user_session', schema='rfx__user')
    op.drop_table('user_action', schema='rfx__user')
    op.drop_table('profile', schema='rfx__user')
    op.drop_table('organization_status', schema='rfx__user')
    op.drop_table('organization_role', schema='rfx__user')
    op.drop_table('organization_delegated_access', schema='rfx__user')
    op.drop_table('user_status', schema='rfx__user')
    op.drop_table('user_identity', schema='rfx__user')
    op.drop_table('ref__system_role', schema='rfx__user')
    op.drop_table('organization', schema='rfx__user')
    op.drop_table('user', schema='rfx__user')
    op.drop_table('ref__role_type', schema='rfx__user')
    op.drop_table('ref__realm', schema='rfx__user')
    op.drop_table('ref__organization_type', schema='rfx__user')
    op.drop_table('ref__action', schema='rfx__user')
    op.drop_table('group', schema='rfx__user')
    # ### end Alembic commands ###
