"""test user

Revision ID: aa79510bd03f
Revises: 9a5904cc863d
Create Date: 2025-11-07 13:27:54.187272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa79510bd03f'
down_revision: Union[str, Sequence[str], None] = '9a5904cc863d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref__provider',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_user_test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref__provider', schema='rfx_user_test')
    # ### end Alembic commands ###
