"""test message

Revision ID: e904b5c41b59
Revises: aa79510bd03f
Create Date: 2025-11-07 13:28:17.716914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e904b5c41b59'
down_revision: Union[str, Sequence[str], None] = 'aa79510bd03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('font_color', sa.String(length=7), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name'),
    schema='rfx_message_test'
    )
    op.create_table('message',
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('rendered_content', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.Enum('TEXT', 'HTML', 'MARKDOWN', 'JSON', 'XML', name='contenttypeenum', schema='rfx_message_test'), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('expirable', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_read_receipt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevelenum', schema='rfx_message_test'), nullable=False),
    sa.Column('message_type', sa.Enum('NOTIFICATION', 'ALERT', 'REMINDER', 'SYSTEM', 'USER', name='messagetypeenum', schema='rfx_message_test'), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatusenum', schema='rfx_message_test'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mtype', sa.String(length=255), nullable=False),
    sa.Column('template_key', sa.String(length=255), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('template_locale', sa.String(length=10), nullable=True),
    sa.Column('template_engine', sa.String(length=32), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('render_strategy', sa.Enum('SERVER', 'CLIENT', 'CACHED', 'STATIC', name='renderstrategyenum', schema='rfx_message_test'), nullable=True),
    sa.Column('render_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CLIENT_RENDERING', 'FAILED', name='renderstatusenum', schema='rfx_message_test'), nullable=True),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_box',
    sa.Column('_txt', postgresql.TSVECTOR(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('email_alias', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('GROUP', 'SINGLE', name='boxtypeenum', schema='rfx_message_test'), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_template',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('render_strategy', sa.Enum('SERVER', 'CLIENT', 'CACHED', 'STATIC', name='renderstrategyenum', schema='rfx_message_test'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='templatestatusenum', schema='rfx_message_test'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('tenant_id', 'app_id', 'key', 'version', 'locale', 'channel', name='uq_template_scope'),
    schema='rfx_message_test'
    )
    op.create_table('ref__role',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('key', '_id'),
    sa.UniqueConstraint('key'),
    schema='rfx_message_test'
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('font_color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('group', sa.Enum('APPLICATION', 'FUNCTION', name='taggroupenum', schema='rfx_message_test'), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('name', '_id'),
    sa.UniqueConstraint('name'),
    schema='rfx_message_test'
    )
    op.create_table('tag_preference',
    sa.Column('option', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('template_render_cache',
    sa.Column('template_key', sa.String(length=255), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('compiled_template', sa.LargeBinary(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('template_key', 'template_version', 'locale', 'channel', name='uq_cache_key'),
    schema='rfx_message_test'
    )
    op.create_table('message_action',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HTTP', 'LINK', name='actiontypeenum', schema='rfx_message_test'), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('authentication', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('host', sa.String(length=1024), nullable=True),
    sa.Column('endpoint', sa.String(length=1024), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'DELETE', 'PATCH', name='httpmethodenum', schema='rfx_message_test'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('mobile_endpoint', sa.String(length=1024), nullable=True),
    sa.Column('destination', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('target', sa.Enum('BLANK', 'IFRAME', name='httptargetenum', schema='rfx_message_test'), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['rfx_message_test.message._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_attachment',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['rfx_message_test.message._id'], ),
    sa.PrimaryKeyConstraint('message_id', '_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_box_user',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['rfx_message_test.message_box._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_embedded',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('host', sa.String(length=1024), nullable=True),
    sa.Column('endpoint', sa.String(length=1024), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['rfx_message_test.message._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_reference',
    sa.Column('_iid', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.String(length=1024), nullable=True),
    sa.Column('resource', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('telecom__email', sa.String(length=255), nullable=True),
    sa.Column('telecom__phone', sa.String(length=12), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['rfx_message_test.message._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_recipient',
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('executed_action_id', sa.UUID(), nullable=True),
    sa.Column('last_reply_id', sa.UUID(), nullable=True),
    sa.Column('box_id', sa.UUID(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('mark_as_read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('is_ignored', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('direction', sa.Enum('NOTIFICATION', 'ALERT', 'REMINDER', 'SYSTEM', 'USER', name='messagetypeenum', schema='rfx_message_test'), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['rfx_message_test.message_box._id'], ),
    sa.ForeignKeyConstraint(['executed_action_id'], ['rfx_message_test.message_action._id'], ),
    sa.ForeignKeyConstraint(['last_reply_id'], ['rfx_message_test.message._id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['rfx_message_test.message._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    op.create_table('message_recipient_action',
    sa.Column('message_recipient_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rfx_message_test.message_action._id'], ),
    sa.ForeignKeyConstraint(['message_recipient_id'], ['rfx_message_test.message_recipient._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_message_test'
    )
    rfx_message_test__message_recipients = PGView(
        schema="rfx_message_test",
        signature="_message_recipients",
        definition='SELECT message._id AS message_id,\n    r.recipient_id,\n    message.subject,\n    message.content,\n    message.content_type,\n    message.sender_id,\n    message.tags,\n    message.expirable,\n    message.priority,\n    message.message_type,\n    r.read AS is_read,\n    r.mark_as_read AS read_at,\n    r._id AS record_id,\n    r.archived\n   FROM rfx_message.message\n     JOIN rfx_message.message_recipient r ON message._id = r.message_id'
    )
    op.create_entity(rfx_message_test__message_recipients)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    rfx_message_test__message_recipients = PGView(
        schema="rfx_message_test",
        signature="_message_recipients",
        definition='SELECT message._id AS message_id,\n    r.recipient_id,\n    message.subject,\n    message.content,\n    message.content_type,\n    message.sender_id,\n    message.tags,\n    message.expirable,\n    message.priority,\n    message.message_type,\n    r.read AS is_read,\n    r.mark_as_read AS read_at,\n    r._id AS record_id,\n    r.archived\n   FROM rfx_message.message\n     JOIN rfx_message.message_recipient r ON message._id = r.message_id'
    )
    op.drop_entity(rfx_message_test__message_recipients)

    op.drop_table('message_recipient_action', schema='rfx_message_test')
    op.drop_table('message_recipient', schema='rfx_message_test')
    op.drop_table('message_reference', schema='rfx_message_test')
    op.drop_table('message_embedded', schema='rfx_message_test')
    op.drop_table('message_box_user', schema='rfx_message_test')
    op.drop_table('message_attachment', schema='rfx_message_test')
    op.drop_table('message_action', schema='rfx_message_test')
    op.drop_table('template_render_cache', schema='rfx_message_test')
    op.drop_table('tag_preference', schema='rfx_message_test')
    op.drop_table('tag', schema='rfx_message_test')
    op.drop_table('ref__role', schema='rfx_message_test')
    op.drop_table('message_template', schema='rfx_message_test')
    op.drop_table('message_box', schema='rfx_message_test')
    op.drop_table('message', schema='rfx_message_test')
    op.drop_table('label', schema='rfx_message_test')
    # ### end Alembic commands ###
