"""test media

Revision ID: aefd82bc7460
Revises: 9479f0daa895
Create Date: 2025-11-07 13:29:20.483070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefd82bc7460'
down_revision: Union[str, Sequence[str], None] = '9479f0daa895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media-entry',
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('filehash', sa.CHAR(length=64), nullable=True),
    sa.Column('filemime', sa.String(length=256), nullable=True),
    sa.Column('fskey', sa.String(length=24), nullable=True),
    sa.Column('length', sa.BigInteger(), nullable=False),
    sa.Column('fspath', sa.String(length=1024), nullable=True),
    sa.Column('compress', sa.Enum('BZ2', 'GZIP', 'LZ4', 'LZMA', 'SNAPPY', 'XZ', 'ZIP', 'ZSTD', name='fsspeccompressionmethod', schema='rfx_media_test'), nullable=True),
    sa.Column('resource', sa.String(length=24), nullable=True),
    sa.Column('resource__id', sa.UUID(), nullable=True),
    sa.Column('resource_sid', sa.UUID(), nullable=True),
    sa.Column('resource_iid', sa.UUID(), nullable=True),
    sa.Column('xattrs', sa.String(length=256), nullable=True),
    sa.Column('cdn_exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cdn_url', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='rfx_media_test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media-entry', schema='rfx_media_test')
    # ### end Alembic commands ###
