__name__ = 'rfx-base'
__title__ = 'RFX Base Platform'
__version__ = '0.5.1'
__author__ = 'RFX JSC'
__author_email__ = ''
__description__ = 'Backend platform for RFX JSC projects built on Fluvius with DDD and CQRS—foundational domain modules for identity, messaging, client workflows, and enterprise integrations.'
__url__ = ''
__license__ = 'GPL-3.0-or-later'
__copyright__ = ''
__keywords__ = ['rfx', 'fluvius', 'ddd', 'cqrs', 'fastapi', 'async', 'postgresql']
__build_no__ = 0
__build_ts__ = 1776671508
