# DB_DSN = None

DEFAULT_SERVICE_CLIENT = None
MESSAGE_CLIENT = DEFAULT_SERVICE_CLIENT
NOTIFY_CLIENT = DEFAULT_SERVICE_CLIENT
TEMPLATE_CLIENT = DEFAULT_SERVICE_CLIENT

# --- Default Schema Names ---
RFX_CLIENT_SCHEMA = None
RFX_DISCUSS_SCHEMA = None
RFX_MEDIA_SCHEMA = None
RFX_MESSAGE_SCHEMA = None
RFX_NOTIFY_SCHEMA = None
RFX_POLICY_SCHEMA = None
RFX_USER_SCHEMA = None
RFX_QR_SCHEMA = None
RFX_TODO_SCHEMA = None
RFX_TEMPLATE_SCHEMA = None

LOG_LEVEL = None
