DB_DSN = None

DEFAULT_SERVICE_CLIENT = None
MESSAGE_CLIENT = DEFAULT_SERVICE_CLIENT
NOTIFY_CLIENT = DEFAULT_SERVICE_CLIENT
TEMPLATE_CLIENT = DEFAULT_SERVICE_CLIENT

# --- Default Schema Names ---
RFX_CLIENT_SCHEMA = "rfx_client"
RFX_DISCUSS_SCHEMA = "rfx_discuss"
RFX_MEDIA_SCHEMA = "rfx_media"
RFX_MESSAGE_SCHEMA = "rfx_message"
RFX_NOTIFY_SCHEMA = "rfx_notify"
RFX_POLICY_SCHEMA = "rfx_policy"
RFX_USER_SCHEMA = "rfx_user"
RFX_QR_SCHEMA = "rfx_qr"
RFX_TODO_SCHEMA = "rfx_todo"
RFX_TEMPLATE_SCHEMA = "rfx_template"
RFX_HATCHET_SCHEMA = "rfx_hatchet"
RFX_IDM_SCHEMA = "rfx_idm"
RFX_CQRS_SCHEMA = "domain-audit"

LOG_LEVEL = None
