DB_DSN = None


RFX_BILLING_SCHEMA = "rfx_billing"
RFX_CLIENT_SCHEMA = "rfx_client"
RFX_CQRS_SCHEMA = "rfx_cqrs"
RFX_AUDIT_SCHEMA = "domain_audit"
RFX_DISCUSS_SCHEMA = "rfx_discuss"
RFX_DOCMAN_SCHEMA = "rfx_docman"
RFX_FORM_SCHEMA = "rfx_form"
RFX_IDM_SCHEMA = "rfx_idm"
RFX_MEDIA_SCHEMA = "rfx_media"
RFX_MESSAGE_SCHEMA = "rfx_message"
RFX_NOTIFY_SCHEMA = "rfx_notify"
RFX_POLICY_SCHEMA = "rfx_policy"
RFX_USER_SCHEMA = "rfx_user"
RFX_AUDIT_SCHEMA = "rfx_audit"
RFX_QR_SCHEMA = "rfx_qr"
RFX_TODO_SCHEMA = "rfx_todo"
RFX_TEMPLATE_SCHEMA = "rfx_template"
RFX_2DMESSAGE_SCHEMA = "rfx_2dmessage"
DEFAULT_SERVICE_CLIENT = None
MESSAGE_CLIENT = DEFAULT_SERVICE_CLIENT
NOTIFY_CLIENT = DEFAULT_SERVICE_CLIENT
TEMPLATE_CLIENT = DEFAULT_SERVICE_CLIENT


RFX_CLIENT_DB_DSN = None
RFX_DISCUSS_DB_DSN = None
RFX_MEDIA_DB_DSN = None
RFX_MESSAGE_DB_DSN = None
RFX_NOTIFY_DB_DSN = None
RFX_POLICY_DB_DSN = None
RFX_USER_DB_DSN = None
RFX_QR_DB_DSN = None
RFX_TODO_DB_DSN = None
RFX_TEMPLATE_DB_DSN = None
RFX_HATCHET_DB_DSN = None
RFX_IDM_DB_DSN = None
RFX_DOCMAN_DB_DSN = None
RFX_CQRS_DB_DSN = None


LOG_LEVEL = 'INFO'
