from rfx_base import config

LOG_LEVEL = config.LOG_LEVEL
DB_DSN = config.DB_DSN

QR_DOMAIN_NAMESPACE = "rfx-qr"
QR_BIN_ID = None
QR_CONSUMER_ID = None
QR_SERVICE_CODE = None
QR_POINT_OF_INITIATION_METHOD = None
QR_TRANSACTION_CURRENCY = None
QR_STORE_LABEL = None
QR_REFERENCE_LABEL = None

# POLICY_SERVICE_SCHEMA = "rfx_policy"
# POLICY_SCHEMA = config.RFX_POLICY_SCHEMA
# POLICY_TABLE = "_policy__user_profile"
