from rfx_base import config


UAPI_URL = config.UAPI_URL
LINEAR_CONNECTION_ID = config.LINEAR_CONNECTION_ID
DEFAULT_TEAM_ID = config.DEFAULT_TEAM_ID
LINEAR_API_KEY = config.LINEAR_API_KEY
LINEAR_TEAM_ID = config.LINEAR_TEAM_ID
LINEAR_WEBHOOK_SECRET = config.LINEAR_WEBHOOK_SECRET
