from rfx_base import config

LOG_LEVEL = config.LOG_LEVEL
DB_DSN = config.DB_DSN

NOTIFY_SERVICE_SCHEMA = "rfx_notify"
POLICY_SCHEMA = "rfx_policy"
POLICY_TABLE = "_policy__user_profile"
NAMESPACE = "rfx-notify"

# Provider credentials / config placeholders
SENDGRID_API_KEY = None
SENDGRID_FROM_EMAIL = None

SMTP_HOST = None
SMTP_PORT = None
SMTP_USE_TLS = None
SMTP_USERNAME = None
SMTP_PASSWORD = None
SMTP_FROM_EMAIL = None

TWILIO_ACCOUNT_SID = None
TWILIO_AUTH_TOKEN = None
TWILIO_FROM_NUMBER = None

NOTIFY_RATE_LIMIT_PER_MINUTE = 60
NOTIFY_RATE_LIMIT_PER_HOUR = 1000
NOTIFY_RATE_LIMIT_PER_DAY = 10000
