from rfx_base import config

DB_DSN = config.DB_DSN
RFX_CLIENT_SCHEMA = config.RFX_CLIENT_SCHEMA
RFX_POLICY_SCHEMA = config.RFX_POLICY_SCHEMA

RFX_USER_SCHEMA = config.RFX_USER_SCHEMA
RFX_MESSAGE_SCHEMA = config.RFX_MESSAGE_SCHEMA
RFX_DISCUSS_SCHEMA = config.RFX_DISCUSS_SCHEMA

POLICY_TABLE = "_policy__rfx_client"
NAMESPACE = "rfx-client"
DISCUSSION_NAMESPACE = "rfx-discussion"
MESSAGE_NAMESPACE = "rfx-message"

COMMENT_AGGROOTS = "project,ticket,comment"

PROJECT_MANAGEMENT_INTEGRATION_ENABLED = True
PROJECT_MANAGEMENT_INTEGRATION_PROVIDER = "linear"
MESSAGE_ENABLED = True


REALM_NAME = "dev.riverflow.solutions"
