from rfx_base import config

DB_DSN = config.DB_DSN
CPO_CLIENT_SCHEMA = config.RFX_CLIENT_SCHEMA
POLICY_SCHEMA = config.RFX_POLICY_SCHEMA

USER_PROFILE_SCHEMA = config.RFX_USER_SCHEMA
MESSAGE_SERVICE_SCHEMA = config.RFX_MESSAGE_SCHEMA
CPO_DISCUSSION_SCHEMA = config.RFX_DISCUSS_SCHEMA

POLICY_TABLE = "_policy__rfx_client"
NAMESPACE = "rfx-client"
DISCUSSION_NAMESPACE = "rfx-discussion"
MESSAGE_NAMESPACE = "rfx-message"

COMMENT_AGGROOTS = "project,ticket,comment"

PROJECT_MANAGEMENT_INTEGRATION_ENABLED = True
PROJECT_MANAGEMENT_INTEGRATION_PROVIDER = "linear"

UAPI_URL = config.UAPI_URL
LINEAR_CONNECTION_ID = config.LINEAR_CONNECTION_ID
DEFAULT_TEAM_ID = config.DEFAULT_TEAM_ID
LINEAR_API_KEY = config.LINEAR_API_KEY
LINEAR_TEAM_ID = config.LINEAR_TEAM_ID
LINEAR_WEBHOOK_SECRET = config.LINEAR_WEBHOOK_SECRET
